### ISSUE TITLE
flushPartial Legacy Version 5

### ISSUE THREAD

**Issue by siochs** [rei-vilo/PDLS_EXT3_Basic_Global#13]
### Describe the request

I like your library. According to the  [official documentation](https://pdls.pervasivedisplays.com/userguide/Volume3/Chapter3/Section2/#use) there is `partialUpdate()` available in the Legacy Version 5 of this library. I searched in old commits, but I cannot find any implementation. Can you help me out with that?

I am hobbyist and trying to recycle an old shelf label, so no commercial interests in the game here.

### Describe the current behavior

Partial Update routines not available in legacy commits (version 5.x upwards)

### PDLS variant

PDLS_EXT3_Basic_Global

### PDLS version

5.5.0

### IDE or SDK name and version

Arduino SDK, in Platformio

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/vilo/PDLS_EXT3_Basic_Global/issues?q=)
- [X] My request contains all necessary details

**Comment by rei-vilo** [comment]
Hi!

Thank you for your kind words.

The partial update mode is deprecated and no longer supported. The Basic edition didn't include that feature.

I would recommend to use fast update instead, available at [PDLS_EXT3_Basic_Fast](https://github.com/rei-vilo/PDLS_EXT3_Basic_Fast). 

Fast update is marginally slower than partial update but ensures an optimal image quality.

**Comment by siochs** [comment]
Thank you, I would like to do that, but unfortunately my display does not support embedded fast update (E2266JS0C1). Therefore i would like to test the partial update feature on that display, There is no old code somewhere implementing that feature?

**Comment by rei-vilo** [comment]
Partial update runs on and requires fast update. 

If the screen only features global update, fast and partial update modes are not available.

**Comment by siochs** [comment]
Thank you, that clarifies it.
