### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by wspitts2** [rei-vilo/PDLS_EXT3_Basic_Global#2]
You can add support for an ESP32 Devkit v1 using ARDUINO through the following:

const pins_t boardESP32 =
{
 .panelBusy = 14, ///< EXT3 pin 3 Red    -> GPIO14 pin 17 (GPIO)
 .panelDC = 27, ///< EXT3 pin 4 Orange   -> GPIO27 pin 16 (GPIO)
 .panelReset = 26, ///< EXT3 pin 5 Yellow-> GPIO26 pin 15 (GPIO)
 .flashCS = 25, ///< EXT3 pin 8 Violet   -> GPIO25 pin 14 (GPIO)
 .panelCS = 33, ///< EXT3 pin 9 Grey     -> GPIO33 pin 13 (GPIO)
 
 //The below ports are not needed for the 2.66” display base level projects
 //See pin mapping diagram of EXT3 to ESP32 to know if you need any of the below ports
 .panelCSS = NOT_CONNECTED, ///< EXT3 pin 12 Grey2  -> ?
 .flashCSS = NOT_CONNECTED, ///< EXT3 pin 20 Black2  -> ?
 .touchReset = NOT_CONNECTED, ///< Separate touch board
 .touchInt = NOT_CONNECTED, ///< Separate touch board
 .cardCS = NOT_CONNECTED, ///< Separate SD-card board
 .cardDetect = NOT_CONNECTED, ///< Separate SD-card board
};

Here is a link to a tutorial that mirrors the embedded computing blog "Connecting the EXT3 to the Arduino Zero or M0 Pro" and modified for ESP32:
https://docs.google.com/document/d/1n4Jl7uKD6odnbmRgLsNShRXBoZbzR4CFlCR1YncSQME/edit?usp=sharing

**Comment by rei-vilo** [comment]
Thank you very much for exploring the ESP32 with the EXT3 and sharing the configuration. 
​
Please allow me a couple of days to test in-house before adding the extra board and publishing the new configuration.

**Comment by rei-vilo** [comment]
`GPIO14` can't be used as debugging requires it for `TMS` signal.

See added board at

https://github.com/rei-vilo/PDLS_EXT3_Basic/blob/0c1b50afcdc64067470cca1f3ceef4930a83989c/src/hV_Configuration.h#L344-L357

Thank you for sharing the idea!

**Comment by wspitts2** [comment]
Thanks this is awesome. It works on the ESP32 DevKit V1 as well except there is no GPIO0 pin on this board. So, it needs to be remapped to a different for the DevKit V1. The GPIO Pinout can be found here for the DevKit V1:
https://www.mischianti.org/wp-content/uploads/2020/11/ESP32-DOIT-DEV-KIT-v1-pinout-mischianti.png

**Comment by rei-vilo** [comment]
Well, in that case, just use `NOT_CONNECTED` for the unused signals.

```
const pins_t boardESP32DevKitC = 
 { 
     .panelBusy = 27, ///< EXT3 pin 3 Red -> GPIO27 
     .panelDC = 26, ///< EXT3 pin 4 Orange -> GPIO26 
     .panelReset = 25, ///< EXT3 pin 5 Yellow -> GPIO25 
     .flashCS =33, ///< EXT3 pin 8 Violet -> GPIO33 
     .panelCS = 32, ///< EXT3 pin 9 Grey -> GPIO32 
     .panelCSS = NOT_CONNECTED, ///< EXT3 pin 12 Grey2 -> GPIO4 
     .flashCSS = NOT_CONNECTED, ///< EXT3 pin 20 Black2 -> GPIO0 
     .touchReset = NOT_CONNECTED, ///< Separate touch board 
     .touchInt = NOT_CONNECTED, ///< Separate touch board 
     .cardCS = NOT_CONNECTED, ///< Separate SD-card board 
     .cardDetect = NOT_CONNECTED, ///< Separate SD-card board 
 }; 
```
