### ISSUE TITLE
Purpose of the "_flag50" in the PDLS_EXT3_Basic_Fast?

### ISSUE THREAD

**Issue by timov50** [rei-vilo/PDLS_EXT3_Basic_Global#7]
I noticed that in the version 604 there is small change in the COG_Update.
There is defined a new screen dependent boolean variable "_flag50" with the comment: "Specific settings for fast update"

The flag50  is set true for the following display models:
 - 0x150C: // 1.54”
 - 0x210E: // 2.13”
 - 0x260C: // 2.66”
 -  0x370C: // 3.70”
 - 0x430C: // 4.37”

As far as I know, the above is a subset of all fast display models.
(https://www.pervasivedisplays.com/products/?_sft_etc_itc=pu&_sft_product_colour=black-white)

Questions:
What is the purpose of the "_flag50"?  
Is the purpose of the _"flag50" described somewhere in HW documentation of display models?

I patched v602 with the change but I'm not able to see any difference with the 3.7" display.

**Comment by rei-vilo** [comment]
Thank you for reaching out.

## 0x50 for fast update only
 
According to the [Application Note of fast update for small size mono EPDs](https://www.pervasivedisplays.com/wp-content/uploads/2022/09/ApplicationNote_smallSize_fast-update_v02_20220907.pdf), page 22, note 2, `0x50` is required for fast update only.

> 2. Border Setting: this command is only for 1.54”, 2.13”, 2.66”, 3.7” and 4.37”.
> 2.7”, 2.87” and 4.2” don’t need to send this command. 
> CDI is a constant value of 0x07.

`_flag50` is set to `true` for the screens that require this command. It is used for [PDLS_EXT3_Basic_Fast](https://github.com/rei-vilo/PDLS_EXT3_Basic_Fast) and [PDLS_EXT3_Basic_Touch](https://github.com/rei-vilo/PDLS_EXT3_Basic_Touch) which feature fast update.

## Improved consistency across PDLS versions

Release 6.0.4 improves the consistency across the different PDLS versions and thus adds `_flag50` to [PDLS_EXT3_Basic](https://github.com/rei-vilo/PDLS_EXT3_Basic). 

However, it is not used for global update, as per the [Application Note for small size Monochrome EPD with iTC (OTP LUT)](https://www.pervasivedisplays.com/wp-content/uploads/2022/06/ApplicationNote_Small_Size_Mono_v02_220606.pdf), page 19.
